export default {
    users: [],
    user: {}
    // user: {
    //     "email": null,
    //     "code": null,
    //     "userAvatar": null,
    //     "userWallImage": null,
    //     "phoneNumber": null,
    //     "password": null,
    //     "contactCode": null,
    //     "fisrtName": null,
    //     "hrId": null,
    //     "introduceUserId": null,
    //     "lastname": null,
    //     "payLeave": null,
    //     "paidLeave": null,
    //     "unPaidLeave": null,
    //     "userStatus": null,
    //     "typeUser": null,
    //     "createTime": null,
    //     "updateTime": null
    // },
    // userUpdate: {
    //     "email": null,
    //     "code": null,
    //     "userAvatar": null,
    //     "userWallImage": null,
    //     "password": null,
    //     "contactCode": null,
    //     "phoneNumber": null,
    //     "fisrtName": null,
    //     "lastname": null,
    //     "address": null,
    //     "introduceUserId": null,
    //     "hrId": null,
    //     "payLeave": null,
    //     "paidLeave": null,
    //     "unPaidLeave": null,
    //     "userStatus": null,
    //     "typeUser": null,
    //     "createTime": null,
    //     "updateTime": null,
    //     "id": null
    // },
    // filters: {
    //     name: null,
    //     email: null,
    //     phone: null,
    //     hrId: null,
    //     introduceUserId: null,
    // },
}